project:
  type: book

book:
  title: "mtk"
  author: "Jerell James"
  date: "22/04/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - modelingtoolkit.qmd
    - standardlibrary.qmd
    - ai4ecomponents.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

crossref:
  eq-prefix: Eq

date-modified: last-modified
